### ISSUE TITLE
Feature Request: Abstract Tree code from source

### ISSUE THREAD

**Issue by buddha314** [geronimo-iia/async-btree#13]
This may be implemented or contrary to your design goals, so feel free to ignore it.

[Behavior Tree](https://github.com/BehaviorTree/BehaviorTree.CPP) is a well known Behavior Tree package.  That project uses XML to define the tree.  The source c++ relies on extending base classes.  This allows easy re-use of the logic.

From the [async-btree documentation](https://geronimo-iia.github.io/async-btree/) is appears the python functions are decorated directly with the tree.  If so, it may be practical to abstract them from each other.

**Comment by geronimo-iia** [comment]
Hi,

You're right, from an external use, you create your python function for action/condition and compose them with those from this framework.
You could organize them in reusable module as we can do with classic python module. No xml or external configuration need to be use (we stay in a pythonic view).

Functions from async-btree build an abstract tree for you. If you lookup in code, you should see an annotation "node_metadata" on internal implementation.
This abstract tree can be retreived and stringified with 'analyze' and  'stringify_analyze'.
Here the profile:
```def analyze(target: CallableFunction) -> Node # here we have our "abtract tree code"```


For example:
```
# your behaviour tree, or a sub tree:
my_func = alias(child=repeat_until(child=action(hello), condition=success_until_zero), name="btree_1")

# retrieve meta information and build a Node tree
abstract_tree_tree_1 = analyze(my_func) 

# output the tree:
print(stringify_analyze(abstract_tree_tree_1))
```

Hope this can help,

Jerome

**Comment by geronimo-iia** [comment]
I will wrote few doc on this, should be better :)

**Comment by geronimo-iia** [comment]
I've updated readme and documentation web site, let me known if it's clear (it's not my native language...)
Regards,
Jerome

**Comment by buddha314** [comment]
Thank you!  I agree that it should stay pythonic. I think that I will need to try more examples before I fully understand.  Your comments in the README were helpful.
