### ISSUE TITLE
Documentation Request

### ISSUE THREAD

**Issue by buddha314** [geronimo-iia/async-btree#14]
When appropriate, I suggest you could re-create the [first tutorial on BehaviorTree](https://www.behaviortree.dev/tutorial_01_first_tree/) using `async-btree`.  I am far too new to the package, but I have included my attempt here.

```
import async_btree as bt

print("Btreeeeeeee!!!")

async def approach_object():
    """
    A basic node that seems to always accomplish what it sets out to do.
    :return: async_btree.SUCCESS
    """
    return bt.SUCCESS

#async def approach_tree(child_value, other=""):
async def approach_tree():
    """
    Create the tree within Python using existing functions
    :return: bt.sequence()
    """
    status = approach_object()
    await status
    return bt.sequence(children=[approach_object()], succes_threshold=2)


if __name__=="__main__":
    print("Attempting approach")
    seq = approach_tree()
```

I know this is wrong and I will attempt to fix it.  I do think a good example on the doc site would be useful.

Thank you!

**Comment by geronimo-iia** [comment]
Hello,

I've take a look about this tutorial, and i will try to make something similar asap,

Jerome

**Comment by geronimo-iia** [comment]
Here we go : https://geronimo-iia.github.io/async-btree/tutorials/index.html 

I think, I should wrote something about parameters after this one.

Jerome

**Comment by buddha314** [comment]
Fantastic!  When I get a bit more familiar, I will contribute some more examples.  Thank you.
