### ISSUE TITLE
decision nodes success tree is not evaluted

### ISSUE THREAD

**Issue by oliverguhr** [geronimo-iia/async-btree#15]
**Describe the bug**
I am sure I missed something... I tried to extend the example and add a decision node together with the context. The data in the context is correct and the condition is evaluated - however, the success (or failiure) function is not executed. 

**Code to Reproduce**

```
import curio
import async_btree as bt
import contextvars


def some_action():
    print("continue here...")

async def say_hello(name: str):
    print(f"Hello: {name}")

def is_name_set():
    print("current name is " + name.get())
    return name.get() != ""

name = contextvars.ContextVar('name',default="")

greet_with_name = bt.decision(is_name_set, 
        bt.always_success(child=bt.action(target=say_hello, name=name.get()))        
        )

b_tree = bt.sequence(
    children=[
        greet_with_name,        
        bt.always_success(child=bt.action(target=some_action)),        
    ]
)

if __name__ == '__main__':
       
    name = contextvars.ContextVar('name')
    name.set("Hans")    
  
    curio.run(b_tree)

    abstract_tree_tree_1 = bt.analyze(b_tree) 
    # output the tree:
    print(bt.stringify_analyze(abstract_tree_tree_1))

```

**Expected behavior**
The decision node should evaluate the success_tree / failure_tree methods. 

Thank you in advance.

**Comment by geronimo-iia** [comment]
Hello, thanks for the report, i will look that soon,

With a first look, i notice that :
bt.always_success(child=bt.action(target=say_hello, name=name.get()))  
this will always print en empty name, because name.get() is evaluated on btree build and not on runtime.
It should be part of say_hello function.

But i will try it on my side ;)

**Comment by geronimo-iia** [comment]
the function is_name_set should be declared in async way (i think that i should avoid this in the framework for simplicity):

async def is_name_set():
 ...

and use:

async def say_hello():
    print(f"Hello: {name.get()}")

with:

greet_with_name = bt.decision(is_name_set, 
        bt.always_success(child=bt.action(target=say_hello))        
        )

**Comment by oliverguhr** [comment]
Thank you very much! I just (like two minutes ago) figured out that the decision fails with an exception when you invoke `curio.run(greet_with_name)`. Something in `bt.sequence` catches that exception.. maybe it should be rethrown there, or substituted with a hint like "please use async functions".

**Comment by geronimo-iia** [comment]
for exception i realized that my idea of dealing with them with a falsy meaning was ... a very bad idea !
I think that raise exception as they are is a good way, 
and create an operator 'catch' with:
- a fail result or result of optional code to process
- a class exception to catch (?)
could be the good way to handle it IF we want it.

For sync and async function, i worked on async-rx, and i think that i can support both without too much work

I'm currently in holidays, but i will work on it soon,

thanks again for your pull request
Regards
Jerome

**Comment by oliverguhr** [comment]
Thank you for your fast response Jerome. Mh, sounds like a good idea -a technical fail (an exception) and a logical fail (an action that did not yield the expected result) are two different things. As a developer, you might wan't to handle these things diffrently. So a sensors outage would trigger other actions than a failed attempt to grab an object.

However, since the original issue is solved, I will close this. Enjoy your holidays :)
