### ISSUE TITLE
Feature: use sync and async function 

### ISSUE THREAD

**Issue by geronimo-iia** [geronimo-iia/async-btree#16]
Study how we can use sync or async function in action and condition in order to simplify usage

**Comment by oliverguhr** [comment]
Related: Can all function invocations be evaluated as SUCCESS unless they throw an exception?
this could reduce 
```
def some_action():
    print("continue here...")

bt.sequence(
    children=[
        bt.always_success(child=bt.action(target=some_action)),        
    ] 
```
to: 

```
bt.sequence(
    children=[
        some_action,
    ] 
```

**Comment by geronimo-iia** [comment]
I had a work in progress here https://github.com/geronimo-iia/async-btree/tree/v1.1.0,  
if i have enougth time, I'm near to close this issue

**Comment by geronimo-iia** [comment]
I removed exception catch in most part, in order to let the user decide how manage it. I have to wrote few sample about it.
