### ISSUE TITLE
Design question: should a decision with no failure tree fail?

### ISSUE THREAD

**Issue by oliverguhr** [geronimo-iia/async-btree#21]
I am running a bunch of decisions in a sequence. Each decision only checks a condition and executes a function if the condition is true. If the decision has no failure tree and the condition fails, the decision will be return failure and stop the execution of the sequence. 

I solved this issue for me with this "hack". This way the decision will be successful if the condition fails. 

```
some_decision  = bt.decision(condition=i_fail,
        success_tree=bt.always_success(some_action),         
        failure_tree=bt.always_success(lambda x: True)         
        )
```
The question is: Should a missing failure_tree result in a failing decision? Since there is no action that actually failed, the default could be also "success".

**Comment by geronimo-iia** [comment]
Hello, yes, I'm agree with you. 
The decision is in fact a success, and failure tree act as an optional sub tree.
I will apply this change on branch 1.1.0.

**Comment by geronimo-iia** [comment]
With the v1.1.0, you could wrote it like this:
` 
async def i_fail():
    return FAILURE

async def some_action():
    print("continue here...")
    return SUCCESS

    tree = decision(condition=i_fail,
        success_tree=some_action,         
        failure_tree=lambda : 42
        )
    
    assert await tree() == 42
`

**Comment by oliverguhr** [comment]
This looks great! I will upgrade to version 1.1.0 and test this.
