### ISSUE TITLE
How could it raise error rather than catch?

### ISSUE THREAD

**Issue by ZhangSanMo** [geronimo-iia/async-btree#24]
# code
```python
import curio
import async_btree as bt
def div_zero():
    1/0

result = curio.run(bt.action(div_zero))
assert result is not None
```
# question
curio run normaly and return None, but I except it panic !

# expect
The code panic and report trackstack rather than normal running.

**Comment by geronimo-iia** [comment]
Hello, it should raise a ControlFlowException,
I just check quickly with a test unit, and something is wrong as you noticed. 
I dont known yet where this behaviour came from, we stay in touch

**Comment by geronimo-iia** [comment]
I think that : 

- removing all try/catch and ControlFlowException usage
- add few function like failure_on_exception / success_on_exception (func, exception name)

could offer a better way to deal with exception like a normal usage of python syntax do.

**Comment by ZhangSanMo** [comment]
Thank you for your efforts.

**Comment by geronimo-iia** [comment]
In the last release (1.2.0), i made "few" changes about exception handling.
By default, exception are not catch. 
We can ignore (with a falsy meaning) them with `ignore_exception`.
For always_success/always_failure, exception are encaspulated with ControlFlowException and raised.
This permit us to keep exception flow as usual or catch them and manipulate them with another btree branch.
I'm not sure if it's a good idea or not, so don't hesite to share your advice :)
